name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    
jobs:
  build:
    runs-on: macos-14
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'v')
    steps:
      - uses: actions/checkout@main

      - name: Fetch Orion's latest commit
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          latest_commit=$(gh api -H 'Accept: application/vnd.github.sha' \
          /repos/theos/orion/commits/master); echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT
        id: commit

      - uses: actions/cache@v4
        id: cache-theos
        with:
          path: ${{ github.workspace }}/theos
          key: steps.commit.outputs.latest_commit

      - name: Checkout theos/theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
      - name: Pin Orion SwiftPM deps
        run: |
          perl -0pi -e 's/\.package\(url: "https:\/\/github.com\/apple\/swift-argument-parser", from: "1.0.0"\)/.package(url: "https:\/\/github.com\/apple\/swift-argument-parser", exact: "1.6.0")/g' "${{ github.workspace }}/theos/vendor/orion/Package.swift" "${{ github.workspace }}/theos/vendor/orion/Package@swift-5.6.swift"
      - name: Checkout theos/sdks
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: iPhoneOS15.6.sdk
          path: theos/sdks

      - name: Build Tweak
        run: |
          brew install make ldid
          export THEOS=theos
          THEOS=theos gmake package TARGET="iphone:clang:15.6:15.0" FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
